export const novelCategory = [
    { main: 1, sub: 0, title: 'อื่น ๆ' },
    { main: 1, sub: 1, title: 'นิยายวาย' },
    { main: 1, sub: 2, title: 'นิยายรักหวานแหวว' },
    { main: 1, sub: 3, title: 'นิยายซึ้งกินใจ' },
    { main: 1, sub: 4, title: 'นิยายรักดราม่า' },
    { main: 1, sub: 5, title: 'นิทาน วรรณกรรม' },
    { main: 1, sub: 6, title: 'นิยายผจญภัย' },
    { main: 1, sub: 7, title: 'นิยายสืบสวน' },
    { main: 1, sub: 8, title: 'นิยายระทึกขวัญ' },
    { main: 1, sub: 9, title: 'นิยายสงคราม' },
    { main: 1, sub: 10, title: 'ตลก ขบขัน' },
    { main: 1, sub: 11, title: 'กลอน' },
    { main: 1, sub: 12, title: 'นิยายอดีต ปัจจุบัน อนาคต' },
    { main: 1, sub: 13, title: 'จิตวิทยา' },
    { main: 1, sub: 14, title: 'สังคม' },
    { main: 1, sub: 15, title: 'นิยายหักมุม' },
    { main: 1, sub: 16, title: 'นิยายแฟนตาซี' },
    { main: 1, sub: 17, title: 'นิยายกำลังภายใน' },
    { main: 1, sub: 18, title: 'นิยายวิทยาศาสตร์' },
    { main: 1, sub: 19, title: 'แฟนฟิคอื่นๆ' },
    { main: 1, sub: 20, title: '' },
    { main: 1, sub: 21, title: 'นิยายรักคอมเมดี้' },
    { main: 1, sub: 22, title: 'นิยายรักแฟนตาซี' },
    { main: 1, sub: 23, title: 'นิยายรักสีเทา' },
    { main: 1, sub: 24, title: 'นิยายเกมออนไลน์' },
    { main: 1, sub: 25, title: 'นิยายบู๊ แอคชั่น' },
    { main: 1, sub: 26, title: 'แฟนฟิคเกาหลี' },
    { main: 1, sub: 27, title: 'แฟนฟิคไทย' },
    { main: 1, sub: 28, title: 'แฟนฟิคเอเชีย' },
    { main: 1, sub: 29, title: 'แฟนฟิคฝรั่ง' },
    { main: 1, sub: 30, title: 'แฟนฟิคนิยาย การ์ตูน เกม' },
    { main: 2, sub: 0, title: 'อื่นๆ' },
    { main: 2, sub: 1, title: 'ความรู้รอบตัว' },
    { main: 2, sub: 2, title: 'ความรู้เพื่อดำเนินชีวิต' },
    { main: 2, sub: 3, title: 'เกร็ดประวัติศาสตร์' },
    { main: 2, sub: 4, title: 'ความรู้เรื่องเรียน' },
    { main: 2, sub: 5, title: 'ความรู้แอดมิชชั่น' },
    { main: 2, sub: 6, title: 'ความรู้กลเม็ด, เทคนิค' },
    { main: 2, sub: 7, title: 'เกร็ดท่องเที่ยว' },
    { main: 3, sub: 0, title: 'อื่นๆ' },
    { main: 3, sub: 1, title: 'สุขภาพความงาม' },
    { main: 3, sub: 2, title: 'ของอินเทรนด์' },
    { main: 3, sub: 3, title: 'ตามติดคนดัง' },
    { main: 3, sub: 4, title: 'ดนตรี เพลง หนัง' },
    { main: 3, sub: 5, title: 'ดีไซน์ กราฟฟิค' },
    { main: 3, sub: 6, title: 'การ์ตูน เกมส์' },
    { main: 3, sub: 7, title: 'ไอที เทคโนโลยี' },
    { main: 3, sub: 8, title: 'ประสบการณ์ต่างแดน' }
]

export const novelMainCategory = [
    { main: 1, title: 'ฟรีสไตล์' },
    { main: 2, title: 'มีสาระ' },
    { main: 3, title: 'ไลฟ์สไตล์' },
]